name: universal_ui
description: Temporary fix of dart:ui
version: 0.0.1
publish_to: none
repository: https://github.com/sunderee/universal-ui

environment:
  sdk: ">=2.18.6"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
