name: universal_ui
description: Temporary fix of dart:ui
version: 0.0.2
publish_to: none
repository: https://github.com/sunderee/universal-ui

environment:
  sdk: ">=2.19.2"
  flutter: ">=3.7.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
